name: CI

on:
  pull_request:
    branches:
      - 'development'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref }}
    cancel-in-progress: true

jobs:
  lint-and-audit:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}

    - name: Use Node.js 14.15
      uses: actions/setup-node@v3
      with:
        node-version: 14.15
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Set composer token
      run: composer config github-oauth.github.com ${{ secrets.PRIVATE_ACCESS_TOKEN }} 

    - name: Composer Install
      uses: ramsey/composer-install@v1

    - name: SAAS PHPCS check
      if: always()
      uses: chekalsky/phpcs-action@v1
      with:
        phpcs_bin_path: 'web/app/mu-plugins/bsf-saas-billing/vendor/bin/phpcs'

    - name: PHP Syntax Errors
      if: always()
      run: if find . -name ".php" ! -path "./vendor/" ! -path "./admin/bsf-core/*" -exec php -l {} \; | grep "Errors parsing"; then exit 1; fi
